name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Run tests
      run: go test -v ./...

    - name: Build binaries
      run: |
        mkdir -p dist
        
        # Build for different platforms
        GOOS=linux GOARCH=amd64 go build -o dist/workie-linux-amd64 ./cmd/workie
        GOOS=linux GOARCH=arm64 go build -o dist/workie-linux-arm64 ./cmd/workie
        GOOS=darwin GOARCH=amd64 go build -o dist/workie-darwin-amd64 ./cmd/workie
        GOOS=darwin GOARCH=arm64 go build -o dist/workie-darwin-arm64 ./cmd/workie
        GOOS=windows GOARCH=amd64 go build -o dist/workie-windows-amd64.exe ./cmd/workie
        
        # Create checksums
        cd dist
        sha256sum * > checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/workie-*
          dist/checksums.txt
        generate_release_notes: true
        draft: false
        prerelease: false
